version: 2.1

orbs:
  maven: drift/maven@0.1.7

jobs:
  maven-test:
    docker:
      - image: maven
    steps:
      - checkout
      - run: mvn test -DfailIfNoTests=false --settings .circleci.settings.xml
  maven-build:
    docker:
      - image: maven
    steps:
      - checkout
      - run: mvn clean package -DskipTests --settings .circleci.settings.xml
      - run: mvn -s .circleci.settings.xml -DskipTests deploy
  
workflows:
  version: 2
  workflow:
    jobs:
      - maven-test
      - maven-build
